services:
  blender-build:
      image: blender
      build:
        context: .
        args:
          - blender_package_name=${blender_package_name}
          - blender_package_url=${blender_package_url}
          - blender_path=${blender_path}
      volumes:
        - ./input:${folder_input}
        - ./output:${folder_output}
        - ./scripts:${folder_python_scripts}
      env_file:
        - ./.env
  #Renders just a single frame of the render file
  #The default is one
  blender-render:
    image: blender
    command: [
      "${blender_path}/blender",  #Blender Path
      "-noaudio", #Specify No Audio
      "--background", #Run without GUI
      "${folder_input}/${render_input_file}", #File to be rendered needs to be placed after --background
      "--render-output", #Output argument
      "${folder_output}/frame_#####", #Output path and name
      "--python", #Python Option
      "${folder_python_scripts}/${use_script}.py", #Script path and name to run
      "--render-frame", #Frame argument, needs to be the last
      "1" #Frame to render
    ]
    volumes:
      - ./input:${folder_input}
      - ./output:${folder_output}
      - ./scripts:${folder_python_scripts}
    env_file:
      - ./.env
  #Render the animation from the begining to its end
  #Needs testing
  blender-render-anim:
    image: blender
    command: [
      "${blender_path}/blender",  #Blender Path
      "-noaudio", #Specify No Audio
      "--background", #Run without GUI
      "${folder_input}/${render_input_file}", #File to be rendered needs to be placed after --background
      "--render-output", #Output argument
      "${folder_output}/Animation/frame_#####", #Output path and name
      "--python", #Python Option
      "${folder_python_scripts}/${use_script}.py", #Script path and name to run
      "--render-anim" #Render animation instead of single frame
    ]
    volumes:
      - ./input:${folder_input}
      - ./output:${folder_output}
      - ./scripts:${folder_python_scripts}
    env_file:
      - ./.env