# THIS SCRIPT CREATES A CONTAINER AND TELLS BLENDER
# TO RENDER YOUR FILE
#
# STAY ADVISED, YOUR FILES NEED TO BE ON THE RESPECTIVE VOLUME FOLDERS
# SUCH AS: INPUT, OUTPUT, SCRIPTS
# THOSE FOLDERS ARE DIRECTLY CONNECTED TO THE CONTAINER
# ANYTHING YOU DROP THERE WILL BE READABLE FOR BLENDER
#
# IF YOU NEED TO CHANGE THE FILE OR SCRIPT TO BE LOADED
# UPDATE THE .ENV FILE
#
#
#   MADE BY: ROXANNE 'EDGAR' TAKAMURA   
#
#

source ../.env
IF=$(echo $render_input_file|sed -r 's/[/]+/_/g')
echo "Blender File being loaded - ${IF^^}"
(cd ../. && exec docker compose run --detach --name="RENDER-${IF^^}" blender-render)